CREATE TABLE FIRSTCUPUSER (ID BIGINT NOT NULL, AGEDIFFERENCE INTEGER, BIRTHDAY DATE, PRIMARY KEY (ID));
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
